name: Create Discussion

on:
  push:
    branches:
      - main

jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run create-discussion script
        run: node create-discussion.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
