name: Discussion Workflow

on:
  workflow_run:
    workflows: ["Discussion Action"]
    types:
      - completed

jobs:
  display-discussion-content:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display Discussion Content
        run: cat discussion-content.txt
