name: Discussion Created Trigger

on:
  discussion:
    types:
      - created

jobs:
  processDiscussion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: echo "DISCUSSION_NUMBER=${{ github.event.discussion.number }}" >> $GITHUB_ENV

      - name: Trigger discussion logic action
        uses: ./
