name: Discussion Created Trigger

on:
  discussion:
    types:
      - created

jobs:
  processDiscussion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

  
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16'
          
      - name: Install npm dependencies
        run: npm install

      - name: Fetch Discussion Content
        id: discussion
        uses: kiran-godse/demo_repo@main
        with:
          discussion_number: ${{ github.event.discussion.number }}

      - name: Display Discussion Content
        run: echo "${{ steps.discussion.outputs.discussion_content }}"
