name: Discussion Created Trigger

on:
  discussion:
    types:
      - created

jobs:
  processDiscussion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Trigger discussion logic action
        uses: ./.github/workflows/fetch-discussion.yml
