name: Discussion Created Trigger

on:
  discussion:
    types:
      - created

jobs:
  processDiscussion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Discussion Content
        id: discussion
        uses: ./.github/actions/fetch-discussion
        with:
          discussion_number: ${{ github.event.discussion.number }}

      - name: Display Discussion Content
        run: echo "${{ steps.discussion.outputs.discussion_content }}"
